### ISSUE TITLE
Issue: Thanks button disappears after thanking

### ISSUE THREAD

**Issue by sometimesok** [Lanny/ISS#87] opened 2019-12-08 18:18 UTC
Unthank button appears after refreshing the page.

**Comment by Lanny** [comment] 2019-12-09 02:50
Good catch, did some optimizations on thread rendering a couple weeks ago and I think that was the cause since there's a different code-path to render the unthank button after clicking. Will look into it.

**Comment by Lanny** [comment] 2019-12-22 17:42
Fixed as of ab45bba7828c5e3af62b7d872d088fac5cb5c539

**Closed by Lanny** 2019-12-22 17:42 UTC
